title: mdTranslator
tagline:
description:      Describe your website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url: http://adiwg.github.io/mdTranslator
#url: http://localhost:4000

# Owner/author information
owner:
  name:           mdTranslator
  avatar:         logo150.png
  bio:            "Making metadata manageable."
  email:          your@email.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:
  github: adiwg/mdTranslator
  linkedin:
  instagram:
  lastfm:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: News
    url: /news/
  - title: Demo
    url: http://murmuring-sea-5569.herokuapp.com/iso19115
    external: true
  - title: GitHub
    url: https://github.com/adiwg/mdTranslator
    external: true
  - title: ADIwg
    notransform: true
    url: http://adiwg.github.io
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Anchorage
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Gemfile", "Gemfile.lock", "README.md", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
